In [1]:
#Wav2Vec2 is a speech model that accepts a float array corresponding to the raw waveform of the speech signal.
##managing audio files as it needs to sample to 16000 HZ
import librosa
#it is from favebook ai
import torch
#Wav2Vec2 model was trained using connectionist temporal classification (CTC) 
#so the model output has to be decoded using Wav2Vec2CTCTokenizer.
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

c:\Users\dhire\anaconda3\envs\tensorflowhub\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [68]:
#load any audio file of your choice
speech, rate = librosa.load("testrecording_smartbot.wav",sr=16000)

In [69]:
rate

16000

In [70]:
#load pre-trained model and tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [71]:
##convert the speech into tensor and it shoudl be in pytorch format
input_values = tokenizer(speech, return_tensors = 'pt').input_values

In [72]:
input_values

tensor([[ 0.0013,  0.0013,  0.0013,  ...,  0.0173, -0.0176,  0.0744]])

In [73]:
#Store logits (non-normalized predictions)
logits = model(input_values).logits

In [74]:
logits

tensor([[[ 15.0263, -24.5651, -24.2693,  ...,  -5.8067,  -5.9390,  -6.0746],
         [ 14.9257, -24.2793, -23.9839,  ...,  -5.6584,  -5.6132,  -6.1034],
         [ 15.0115, -24.5488, -24.2612,  ...,  -5.7415,  -5.8605,  -6.0855],
         ...,
         [ 15.2862, -24.7801, -24.4864,  ...,  -5.7889,  -6.1346,  -6.0460],
         [ 14.9855, -24.4853, -24.1897,  ...,  -5.5765,  -6.0223,  -6.1416],
         [ 14.7849, -24.3949, -24.1052,  ...,  -5.8031,  -6.1497,  -6.1665]]],
       grad_fn=<ViewBackward0>)

In [75]:
#Store predicted id's
predicted_ids = torch.argmax(logits, dim =-1)

In [76]:
predicted_ids

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 19,  8, 16, 15, 15, 14,  4,  4,
         22,  8, 16, 16,  4, 23, 23, 15,  0,  5,  0,  7,  0, 12,  5,  5,  4,  4,
         11,  0,  0,  5,  0, 15,  0, 23,  0,  0,  4,  4,  0,  0, 17,  0,  0,  5,
          5,  0,  4,  4,  4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18,
          0,  0,  0, 10,  6,  0, 11,  4,  4,  6, 11,  0,  0,  5,  0,  0,  0,  0,
          4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0, 23,  0,
         15,  0,  0,  5,  0,  0,  9,  0,  0,  0,  0, 10,  0,  0, 12,  0,  0,  0,
          7,  0,  9,  9,  0,  0,  0,  0,  8,  0,  0,  0, 20,  0,  0,  0,  4,  4,
          0,  0,  0,  0,  0,

In [77]:
predicted_ids[0]

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 19,  8, 16, 15, 15, 14,  4,  4,
        22,  8, 16, 16,  4, 23, 23, 15,  0,  5,  0,  7,  0, 12,  5,  5,  4,  4,
        11,  0,  0,  5,  0, 15,  0, 23,  0,  0,  4,  4,  0,  0, 17,  0,  0,  5,
         5,  0,  4,  4,  4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18,
         0,  0,  0, 10,  6,  0, 11,  4,  4,  6, 11,  0,  0,  5,  0,  0,  0,  0,
         4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0, 23,  0,
        15,  0,  0,  5,  0,  0,  9,  0,  0,  0,  0, 10,  0,  0, 12,  0,  0,  0,
         7,  0,  9,  9,  0,  0,  0,  0,  8,  0,  0,  0, 20,  0,  0,  0,  4,  4,
         0,  0,  0,  0,  0,  0,  0,  0, 

In [78]:
#decode the audio to generate text
transcriptions = tokenizer.decode(predicted_ids[0])

In [79]:
transcriptions

'COULD YOU PLEASE HELP ME WITH THE SPLENISANOF SMILED BOY HOW IT HE GOING TO HELP US'